management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 106.13.203.27
    virtual-host: /study1
    username: zzy
    password: 666
  zipkin:
      base-url: http://localhost:10020
  sleuth:
    sampler:
      probability: 1.0
